propose:
  description: >
    you are proposing the motion : {motion}.
    come up with a clear argument in favour of motion and a clear argument against the motion.
  expected_output: >
   your clear argument in favour of motion and a clear argument against the motion in concise manner.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    you are opposing the motion : {motion}.
    come up with a clear argument in favour of motion and a clear argument against the motion.
  expected_output: >
   your clear argument in favour of motion and a clear argument against the motion in concise manner.
  agent: debater
  output_file: output/oppose.md

decide:
  description: >
   Review the arguments presented by both sides and determine which side made a more compelling case based on the strength of their arguments, evidence, and overall persuasiveness. The motion is {motion}
  expected_output: >
   You decide which side is more convincing and why.
  agent: judge
  output_file: output/decide.md
